-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 01:49:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accounts` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `account_type` VARCHAR(45) NOT NULL,
  `balance` DOUBLE NOT NULL,
  `date_opened` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `transaction_type` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `transaction_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `idTransactions_UNIQUE` (`transaction_id` ASC) VISIBLE,
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `salary` DOUBLE NOT NULL,
  `date_hired` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Branches` (
  `branch_id` INT NOT NULL,
  `branch_name` VARCHAR(45) NOT NULL,
  `branch_address` VARCHAR(45) NOT NULL,
  `manager_id` INT NOT NULL,
  PRIMARY KEY (`branch_id`),
  INDEX `manager_id_idx` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `manager_id`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`Employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee_branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee_branch` (
  `employee_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  INDEX `employee_id_idx` (`employee_id` ASC) VISIBLE,
  INDEX `branch_id_idx` (`branch_id` ASC) VISIBLE,
  PRIMARY KEY (`employee_id`, `branch_id`),
  CONSTRAINT `employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`Employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `branch_id`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`Branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loans` (
  `loan_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `loan_amount` DOUBLE NOT NULL,
  `interest_rate` DOUBLE NOT NULL,
  `loan_duration` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`loan_id`),
  UNIQUE INDEX `loan_id_UNIQUE` (`loan_id` ASC) VISIBLE,
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loan_Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loan_Payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `loan_id` INT NOT NULL,
  `payment_amount` DOUBLE NOT NULL,
  `payment_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE INDEX `loan_id_UNIQUE` (`payment_id` ASC) VISIBLE,
  INDEX `loan_id_idx` (`loan_id` ASC) VISIBLE,
  CONSTRAINT `loan_id`
    FOREIGN KEY (`loan_id`)
    REFERENCES `mydb`.`Loans` (`loan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cards` (
  `card_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `card_number` INT NOT NULL,
  `card_type` VARCHAR(45) NOT NULL,
  `expiration_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`card_id`),
  UNIQUE INDEX `card_id_UNIQUE` (`card_id` ASC) VISIBLE,
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ATM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ATM` (
  `atm_id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `installation_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`atm_id`),
  UNIQUE INDEX `atm_id_UNIQUE` (`atm_id` ASC) VISIBLE,
  INDEX `branch_id_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `branch_id`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`Branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transfers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transfers` (
  `transfer_id` INT NOT NULL AUTO_INCREMENT,
  `sender_account_id` INT NOT NULL,
  `receiver_account_id` INT NOT NULL,
  `amount` DOUBLE NOT NULL,
  `transfer_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`transfer_id`),
  UNIQUE INDEX `transfer_id_UNIQUE` (`transfer_id` ASC) VISIBLE,
  INDEX `sender_account_id_idx` (`sender_account_id` ASC) VISIBLE,
  INDEX `receiver_account_id_idx` (`receiver_account_id` ASC) VISIBLE,
  CONSTRAINT `sender_account_id`
    FOREIGN KEY (`sender_account_id`)
    REFERENCES `mydb`.`Accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `receiver_account_id`
    FOREIGN KEY (`receiver_account_id`)
    REFERENCES `mydb`.`Accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointments` (
  `appointment_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `employee_id` VARCHAR(45) NOT NULL,
  `appointment_date` VARCHAR(45) NOT NULL,
  `appointment_time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`appointment_id`),
  UNIQUE INDEX `appointment_id_UNIQUE` (`appointment_id` ASC) VISIBLE,
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_id`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `mydb`.`Employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
